# Model parameters
window_size: 100  # 5 seconds at 20Hz
window_overlap: 0.5
sampling_rate: 20
hidden_size: 64
n_lstm_layers: 2
dropout: 0.5

# Training parameters
batch_size: 32
num_workers: 4
seed: 42
