# MLflow settings
experiment_name: "WISDM Activity Recognition"
run_id: null  # if null, will use latest run with metrics

# Output settings
output_dir: "plots"

# Plot style
style: "darkgrid"
figure_size: [12, 8]
dpi: 300

# Metrics to plot
metrics:
  loss:
    metrics: ["train_loss", "val_loss"]
    ylabel: "Loss"
  accuracy:
    metrics: ["train_acc", "val_acc", "test_acc"]
    ylabel: "Accuracy"
  f1:
    metrics: ["train_f1", "val_f1", "test_f1"]
    ylabel: "F1 Score"

# Plot styling
markers:
  train: "o"
  val: "s"
  test: "^"

colors:
  train: "#2ecc71"
  val: "#e74c3c"
  test: "#3498db"
